name: Flick Pick Deployment

on:
  push:
    branches: ["prod"]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"

      - name: Enable web support
        working-directory: ./frontend
        run: flutter config --enable-web

      - name: Get dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Build and Deploy
        run: |
          cd frontend
          flutter build web --release \
            --dart-define=IS_WEB=true \
            --dart-define=API_URL=${{ secrets.API_URL }} \
            --dart-define=DISPLAY_SKIP_BUTTON=${{ secrets.DISPLAY_SKIP_BUTTON }}
          npm install --global vercel
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --cwd build/web
