name: Flick Pick Deployment

on:
  push:
    branches: ["prod"]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"

      - name: Enable web support
        working-directory: ./frontend
        run: flutter config --enable-web

      - name: Get dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Ensure .env exists for assets
        run: |
          mkdir -p frontend
          if [ ! -f frontend/.env ]; then
            printf "API_URL=\nDISPLAY_SKIP_BUTTON=false\n" > frontend/.env
          fi

      - name: Build Flutter Web
        working-directory: ./frontend
        run: |
          flutter build web --release \
          --dart-define=API_URL=${{ secrets.API_URL }} \
          --dart-define=DISPLAY_SKIP_BUTTON=${{ secrets.DISPLAY_SKIP_BUTTON }} \
          --no-wasm-dry-run

      - name: Deploy to Vercel
        run: |
          npm install --global vercel
          vercel --prod --yes --cwd frontend/build/web --confirm
