name: Flick Pick Deployment

on:
  push:
    branches: ["prod"]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web version
        run: flutter build web

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --cwd build/web
